# Generated by Django 5.2 on 2026-02-06 02:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('account_type', models.CharField(choices=[('checking', 'Checking'), ('credit_card', 'Credit Card'), ('manual', 'Manual')], max_length=20)),
                ('closing_day', models.IntegerField(blank=True, null=True)),
                ('due_day', models.IntegerField(blank=True, null=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BalanceOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month_str', models.CharField(max_length=7, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-month_str'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category_type', models.CharField(choices=[('Fixo', 'Fixo'), ('Variavel', 'Variável'), ('Income', 'Income'), ('Investimento', 'Investimento')], default='Variavel', max_length=20)),
                ('default_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('due_day', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RenameRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=200, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['keyword'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api.category')),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
                'ordering': ['name'],
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='CategorizationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=200, unique=True)),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='api.category')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='api.subcategory')),
            ],
            options={
                'ordering': ['-priority', 'keyword'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('description', models.CharField(max_length=500)),
                ('description_original', models.CharField(blank=True, max_length=500)),
                ('raw_description', models.CharField(blank=True, max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source_file', models.CharField(blank=True, max_length=200)),
                ('is_installment', models.BooleanField(default=False)),
                ('installment_info', models.CharField(blank=True, max_length=20)),
                ('is_recurring', models.BooleanField(default=False)),
                ('is_internal_transfer', models.BooleanField(default=False)),
                ('invoice_month', models.CharField(blank=True, db_index=True, max_length=7)),
                ('invoice_close_date', models.DateField(blank=True, null=True)),
                ('invoice_payment_date', models.DateField(blank=True, null=True)),
                ('month_str', models.CharField(db_index=True, max_length=7)),
                ('is_manually_categorized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='api.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='api.category')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='api.subcategory')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month_str', models.CharField(db_index=True, max_length=7)),
                ('status', models.CharField(choices=[('mapped', 'Mapped'), ('missing', 'Missing'), ('suggested', 'Suggested'), ('skipped', 'Skipped')], default='missing', max_length=20)),
                ('expected_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_mappings', to='api.category')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_mappings', to='api.transaction')),
            ],
            options={
                'ordering': ['month_str', 'category__display_order'],
            },
        ),
        migrations.CreateModel(
            name='BudgetConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month_str', models.CharField(max_length=7)),
                ('limit_override', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_configs', to='api.category')),
            ],
            options={
                'ordering': ['month_str'],
                'unique_together': {('category', 'month_str')},
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['month_str', 'account'], name='api_transac_month_s_1302bb_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category', 'month_str'], name='api_transac_categor_7e4fa5_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date', 'amount', 'account'], name='api_transac_date_fa0025_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recurringmapping',
            unique_together={('category', 'month_str')},
        ),
    ]
