# Generated by Django 5.2 on 2026-02-06 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recurringmapping',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='recurringmapping',
            name='custom_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='recurringmapping',
            name='custom_type',
            field=models.CharField(blank=True, choices=[('Fixo', 'Fixo'), ('Variavel', 'Variável'), ('Income', 'Income'), ('Investimento', 'Investimento')], max_length=20),
        ),
        migrations.AddField(
            model_name='recurringmapping',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recurringmapping',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_mappings', to='api.category'),
        ),
        migrations.AddConstraint(
            model_name='recurringmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', False)), fields=('category', 'month_str'), name='unique_category_month_non_null'),
        ),
    ]
