# Generated by Django 5.2 on 2026-02-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recurring_mapping_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringmapping',
            name='match_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('category', 'Category')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='recurringmapping',
            name='transactions',
            field=models.ManyToManyField(blank=True, related_name='recurring_mapping_links', to='api.transaction'),
        ),
    ]
