# Generated by Django 5.2 on 2026-02-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_multi_transaction_and_match_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurringmapping',
            options={'ordering': ['month_str', 'display_order', 'category__display_order']},
        ),
        migrations.AddField(
            model_name='recurringmapping',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
