# Generated by Django 5.2 on 2026-02-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_display_order_to_recurring_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringmapping',
            name='cross_month_transactions',
            field=models.ManyToManyField(blank=True, related_name='cross_month_links', to='api.transaction'),
        ),
    ]
