# Generated by Django 5.2 on 2026-02-07 16:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_cross_month_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('category_total', 'Category Total Spending'), ('category_remaining', 'Category Budget Remaining')], max_length=30)),
                ('label', models.CharField(max_length=100)),
                ('config', models.JSONField(default=dict)),
                ('color', models.CharField(default='var(--color-accent)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='MetricasOrderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month_str', models.CharField(max_length=20, unique=True)),
                ('card_order', models.JSONField(default=list)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-month_str'],
            },
        ),
    ]
