# Generated by Django 5.2 on 2026-02-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_metricas_order_and_custom_metric'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricasorderconfig',
            name='hidden_cards',
            field=models.JSONField(default=list),
        ),
    ]
