# Generated by Django 5.2 on 2026-02-07 22:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_hidden_cards_to_metricas_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('template_type', models.CharField(choices=[('Fixo', 'Fixo'), ('Income', 'Income'), ('Investimento', 'Investimento')], max_length=20)),
                ('default_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('due_day', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='recurringmapping',
            options={'ordering': ['month_str', 'display_order', 'template__display_order']},
        ),
        migrations.RemoveConstraint(
            model_name='recurringmapping',
            name='unique_category_month_non_null',
        ),
        migrations.AlterUniqueTogether(
            name='budgetconfig',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='budgetconfig',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_configs', to='api.category'),
        ),
        migrations.AlterField(
            model_name='recurringmapping',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_matched_mappings', to='api.category'),
        ),
        migrations.AddField(
            model_name='budgetconfig',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_configs', to='api.recurringtemplate'),
        ),
        migrations.AddField(
            model_name='recurringmapping',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_mappings', to='api.recurringtemplate'),
        ),
        migrations.AddConstraint(
            model_name='recurringmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('template__isnull', False)), fields=('template', 'month_str'), name='unique_template_month_non_null'),
        ),
    ]
