# Generated by Django 5.2 on 2026-02-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_migrate_category_templates_to_recurring_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommetric',
            name='metric_type',
            field=models.CharField(choices=[('category_total', 'Category Total Spending'), ('category_remaining', 'Category Budget Remaining'), ('fixo_total', 'Fixed Expenses Total'), ('investimento_total', 'Investment Total'), ('income_total', 'Income Total'), ('recurring_item', 'Specific Recurring Item'), ('builtin_clone', 'Clone of Built-in Card')], max_length=30),
        ),
    ]
