# Generated by Django 5.2 on 2026-02-09 17:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_expand_custom_metric_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='recurringmapping',
            name='unique_template_month_non_null',
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='balanceoverride',
            name='month_str',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='categorizationrule',
            name='keyword',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='metricasorderconfig',
            name='month_str',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='recurringtemplate',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='renamerule',
            name='keyword',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='account',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='api.profile'),
        ),
        migrations.AddField(
            model_name='balanceoverride',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balance_overrides', to='api.profile'),
        ),
        migrations.AddField(
            model_name='budgetconfig',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_configs', to='api.profile'),
        ),
        migrations.AddField(
            model_name='categorizationrule',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorization_rules', to='api.profile'),
        ),
        migrations.AddField(
            model_name='category',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.profile'),
        ),
        migrations.AddField(
            model_name='custommetric',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_metrics', to='api.profile'),
        ),
        migrations.AddField(
            model_name='metricasorderconfig',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metricas_order_configs', to='api.profile'),
        ),
        migrations.AddField(
            model_name='recurringmapping',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_mappings', to='api.profile'),
        ),
        migrations.AddField(
            model_name='recurringtemplate',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_templates', to='api.profile'),
        ),
        migrations.AddField(
            model_name='renamerule',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rename_rules', to='api.profile'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api.profile'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('profile', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='balanceoverride',
            unique_together={('profile', 'month_str')},
        ),
        migrations.AlterUniqueTogether(
            name='categorizationrule',
            unique_together={('profile', 'keyword')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('profile', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='metricasorderconfig',
            unique_together={('profile', 'month_str')},
        ),
        migrations.AlterUniqueTogether(
            name='recurringtemplate',
            unique_together={('profile', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='renamerule',
            unique_together={('profile', 'keyword')},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['profile', 'month_str'], name='api_transac_profile_610c79_idx'),
        ),
        migrations.AddConstraint(
            model_name='recurringmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('template__isnull', False)), fields=('profile', 'template', 'month_str'), name='unique_profile_template_month'),
        ),
    ]
