# Generated by Django 5.2 on 2026-02-09 17:22

from django.db import migrations


def assign_to_palmer(apps, schema_editor):
    """Create default 'Palmer' profile and assign all existing data to it."""
    Profile = apps.get_model('api', 'Profile')
    palmer, _ = Profile.objects.get_or_create(name='Palmer', defaults={'is_active': True})

    # All models that have a profile FK
    model_names = [
        'Account', 'Category', 'Subcategory', 'CategorizationRule',
        'RenameRule', 'RecurringTemplate', 'Transaction', 'RecurringMapping',
        'BudgetConfig', 'BalanceOverride', 'MetricasOrderConfig', 'CustomMetric',
    ]
    for model_name in model_names:
        Model = apps.get_model('api', model_name)
        count = Model.objects.filter(profile__isnull=True).update(profile=palmer)
        if count:
            print(f'  Assigned {count} {model_name} records to Palmer')


def reverse_assign(apps, schema_editor):
    """Reverse: set profile to NULL on all records."""
    model_names = [
        'Account', 'Category', 'Subcategory', 'CategorizationRule',
        'RenameRule', 'RecurringTemplate', 'Transaction', 'RecurringMapping',
        'BudgetConfig', 'BalanceOverride', 'MetricasOrderConfig', 'CustomMetric',
    ]
    for model_name in model_names:
        Model = apps.get_model('api', model_name)
        Model.objects.all().update(profile=None)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_profile_model_and_fks'),
    ]

    operations = [
        migrations.RunPython(assign_to_palmer, reverse_assign),
    ]
