# Generated by Django 5.2 on 2026-02-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_assign_existing_data_to_palmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='savings_target_pct',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Target savings percentage of income (e.g. 20 means 20%)', max_digits=5),
        ),
    ]
