# Generated by Django 5.2 on 2026-02-12 03:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_setup_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('author_name', models.CharField(help_text='Free-text author name, e.g. "Palmer" or "Rafa"', max_length=100)),
                ('pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-pinned', '-updated_at'],
            },
        ),
        migrations.AlterField(
            model_name='setuptemplate',
            name='template_data',
            field=models.JSONField(default=dict, help_text='Full wizard state snapshot (bank_accounts, categories, recurring, rules, metricas, targets, etc.)'),
        ),
    ]
