# Generated by Django 5.2 on 2026-02-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_family_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='default_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
