# Generated by Django 5.2 on 2026-03-05 02:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_add_balance_anchor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hourly_rate_usd', models.DecimalField(decimal_places=2, help_text='USD per hour', max_digits=8)),
                ('hours_per_day', models.DecimalField(decimal_places=1, default=8.0, max_digits=4)),
                ('wise_fee_pct', models.DecimalField(decimal_places=4, default=0.0116, help_text='Wise transfer fee as decimal (0.0116 = 1.16%)', max_digits=5)),
                ('tax_hold_pct', models.DecimalField(decimal_places=4, default=0.08, help_text='% of BRL kept in enterprise for taxes', max_digits=5)),
                ('advance_total_usd', models.DecimalField(decimal_places=2, default=0, help_text='Total advance to be recouped', max_digits=10)),
                ('advance_recoup_pct', models.DecimalField(decimal_places=4, default=0, help_text='% deducted per payment (e.g. 0.125 = 12.5%)', max_digits=5)),
                ('advance_start_date', models.CharField(blank=True, help_text='First deduction month (YYYY-MM)', max_length=7)),
                ('advance_num_cycles', models.IntegerField(default=0, help_text='Number of pay cycles to deduct')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('income_template', models.ForeignKey(blank=True, help_text='Income template to update with projected salary', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.recurringtemplate')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_config', to='api.profile')),
            ],
        ),
    ]
