# Generated by Django 5.2 on 2026-03-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_add_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryconfig',
            name='wise_fee_flat',
            field=models.DecimalField(decimal_places=2, default=0.46, help_text='Wise flat fee in USD per transfer', max_digits=6),
        ),
        migrations.AlterField(
            model_name='salaryconfig',
            name='wise_fee_pct',
            field=models.DecimalField(decimal_places=4, default=0.0091, help_text='Wise variable fee as decimal (0.0091 = 0.91%)', max_digits=5),
        ),
    ]
