# Generated by Django 5.2 on 2026-03-05 16:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_add_wise_fee_flat'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='pluggy_category',
            field=models.CharField(blank=True, default='', help_text='Original category from Pluggy Open Finance', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pluggy_category_id',
            field=models.CharField(blank=True, default='', help_text='Pluggy category ID (e.g. 10000000)', max_length=20),
        ),
        migrations.CreateModel(
            name='PluggyCategoryMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pluggy_category_id', models.CharField(help_text='Pluggy category ID (e.g. 10000000)', max_length=20)),
                ('pluggy_category_name', models.CharField(help_text='Pluggy category display name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pluggy_mappings', to='api.category')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pluggy_category_mappings', to='api.profile')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pluggy_mappings', to='api.subcategory')),
            ],
            options={
                'ordering': ['pluggy_category_id'],
                'unique_together': {('profile', 'pluggy_category_id')},
            },
        ),
    ]
