# Generated by Django 5.2 on 2026-03-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_consolidate_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='card_last4',
            field=models.CharField(blank=True, default='', help_text='Last 4 digits of credit card (from Pluggy creditCardMetadata)', max_length=4),
        ),
    ]
