# Generated by Django 5.2 on 2026-03-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_add_card_last4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtemplate',
            name='template_type',
            field=models.CharField(choices=[('Fixo', 'Fixo'), ('Income', 'Income'), ('Investimento', 'Investimento'), ('Cartao', 'Cartao')], max_length=20),
        ),
    ]
