# Generated by Django 5.2 on 2026-03-09 20:05

from django.db import migrations


def seed_cartao_templates(apps, schema_editor):
    """Create Cartao recurring templates from existing CC accounts."""
    Account = apps.get_model('api', 'Account')
    RecurringTemplate = apps.get_model('api', 'RecurringTemplate')

    cc_accounts = Account.objects.filter(account_type='credit_card')
    for acct in cc_accounts:
        RecurringTemplate.objects.get_or_create(
            name=acct.name,
            profile=acct.profile,
            template_type='Cartao',
            defaults={
                'default_limit': 0,  # Expected comes from fatura dynamically
                'due_day': 10,  # Typical CC due day
                'is_active': True,
                'display_order': 0,
            },
        )


def reverse(apps, schema_editor):
    RecurringTemplate = apps.get_model('api', 'RecurringTemplate')
    RecurringTemplate.objects.filter(template_type='Cartao').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_add_cartao_template_type'),
    ]

    operations = [
        migrations.RunPython(seed_cartao_templates, reverse),
    ]
