# Generated by Django 5.2 on 2026-04-02 01:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_seed_cartao_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(help_text='Google account email', max_length=200)),
                ('token_data', models.JSONField(help_text='OAuth token JSON: access_token, refresh_token, token_uri, client_id, client_secret, scopes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_accounts', to='api.profile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalendarSelection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calendar_id', models.CharField(help_text='Google Calendar ID (email-like string)', max_length=300)),
                ('calendar_name', models.CharField(help_text='Display name', max_length=200)),
                ('color', models.CharField(blank=True, help_text='Hex color override', max_length=7)),
                ('show_in_home', models.BooleanField(default=False)),
                ('show_in_personal', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_selections', to='api.profile')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='api.googlecalendaraccount')),
            ],
            options={
                'ordering': ['calendar_name'],
                'unique_together': {('profile', 'account', 'calendar_id')},
            },
        ),
    ]
