# Generated by Django 5.2 on 2026-04-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_rename_google_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='google_email',
            field=models.EmailField(blank=True, help_text='Google account email used for login', max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='google_name',
            field=models.CharField(blank=True, help_text='Google display name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='google_picture',
            field=models.URLField(blank=True, help_text='Google profile picture URL', max_length=500, null=True),
        ),
    ]
