# Generated by Django 5.2 on 2026-04-04 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_profile_google_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.JSONField(default=dict, help_text='Full dashboard state: tabs, widgets, configs')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_state', to='api.profile')),
            ],
        ),
    ]
