# Generated by Django 5.2 on 2026-04-06 14:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_dashboard_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICSFeed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name (e.g. Work Calendar)', max_length=200)),
                ('url', models.URLField(help_text='ICS feed URL', max_length=500)),
                ('color', models.CharField(default='#4285f4', help_text='Hex color for events', max_length=7)),
                ('show_in_home', models.BooleanField(default=False)),
                ('show_in_personal', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ics_feeds', to='api.profile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
