# Generated by Django 5.2 on 2026-05-02 20:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_ics_feed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confirmada_em', models.DateField(help_text='Date the pregnancy was confirmed')),
                ('dum', models.DateField(blank=True, help_text='Data da última menstruação', null=True)),
                ('dpp', models.DateField(blank=True, help_text='Data provável do parto (Naegele or USG-corrected)', null=True)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('finalizada', 'Finalizada (parto)'), ('perda', 'Perda gestacional')], default='ativa', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gestante', models.ForeignKey(help_text='The pregnant parent (e.g. Rafa)', on_delete=django.db.models.deletion.CASCADE, related_name='pregnancies_as_gestante', to='api.profile')),
                ('titular', models.ForeignKey(help_text='The non-gestational parent (e.g. Palmer)', on_delete=django.db.models.deletion.CASCADE, related_name='pregnancies_as_titular', to='api.profile')),
            ],
            options={
                'verbose_name_plural': 'Pregnancies',
                'ordering': ['-confirmada_em'],
            },
        ),
        migrations.CreateModel(
            name='HealthExam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('hemograma', 'Hemograma'), ('bioquimica', 'Bioquímica'), ('hormonal', 'Hormonal'), ('sorologia', 'Sorologia'), ('urina', 'Urina'), ('genetico', 'Genético'), ('imagem_rx', 'Raio-X'), ('imagem_us', 'Ultrassom'), ('imagem_ct', 'Tomografia'), ('imagem_rm', 'Ressonância'), ('densitometria', 'Densitometria'), ('cardio', 'Cardiológico'), ('outro', 'Outro')], max_length=30)),
                ('nome', models.CharField(help_text='ex: "Hemograma Completo 2024", "USG Morfológica 2tri"', max_length=200)),
                ('data', models.DateField()),
                ('valores', models.JSONField(blank=True, default=dict, help_text='Normalized fields. Hemograma: {hb, ht, leuco, plaq...}. USG: {ig, peso_fetal, biometria...}')),
                ('arquivo_path', models.CharField(blank=True, help_text='Local path on Mac (relative to ~/Documents) — file://... when opened from desktop', max_length=500)),
                ('laboratorio', models.CharField(blank=True, max_length=200)),
                ('medico', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_exams', to='api.profile')),
                ('pregnancy', models.ForeignKey(blank=True, help_text='Optional link to a pregnancy if this exam is part of pre-natal care', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='api.pregnancy')),
            ],
            options={
                'ordering': ['-data', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrenatalConsultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('ig_semanas', models.CharField(blank=True, help_text='Idade gestacional, ex: "8+3"', max_length=10)),
                ('obstetra', models.CharField(blank=True, max_length=200)),
                ('pa_sis', models.IntegerField(blank=True, null=True)),
                ('pa_dia', models.IntegerField(blank=True, null=True)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fcf_bpm', models.IntegerField(blank=True, null=True)),
                ('altura_uterina_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('queixas', models.TextField(blank=True)),
                ('conduta', models.TextField(blank=True)),
                ('proxima_consulta', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='api.pregnancy')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='VitalReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('peso', 'Peso (kg)'), ('altura', 'Altura (cm)'), ('pa_sis', 'PA Sistólica (mmHg)'), ('pa_dia', 'PA Diastólica (mmHg)'), ('fc', 'Frequência Cardíaca (bpm)'), ('temp', 'Temperatura (°C)'), ('glicemia', 'Glicemia (mg/dL)'), ('imc', 'IMC'), ('cintura', 'Circunferência Abdominal (cm)'), ('fcf', 'FCF Fetal (bpm)'), ('au', 'Altura Uterina (cm)')], max_length=20)),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pregnancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitals', to='api.pregnancy')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_readings', to='api.profile')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
