# Generated by Django 5.2 on 2026-05-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_pregnancy_healthexam_prenatalconsultation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregnancy',
            name='carencia_obstetrica_dias',
            field=models.IntegerField(default=300, help_text='Dias de carência obstétrica do plano'),
        ),
        migrations.AddField(
            model_name='pregnancy',
            name='plano_nome',
            field=models.CharField(blank=True, help_text='Ex: Amil 702 PME', max_length=100),
        ),
        migrations.AddField(
            model_name='pregnancy',
            name='plano_vigencia_inicio',
            field=models.DateField(blank=True, help_text='Início vigência do plano de saúde', null=True),
        ),
    ]
