# Generated by Django 5.2 on 2026-05-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_pregnancy_carencia_obstetrica_dias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthexam',
            name='checkpoint_id',
            field=models.CharField(blank=True, help_text='Stable id of the prenatal checkpoint this exam fulfills (e.g. "usg-datacao", "totg")', max_length=50),
        ),
    ]
