# Generated by Django 5.2 on 2026-05-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_healthexam_checkpoint_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalreading',
            name='tipo',
            field=models.CharField(choices=[('peso', 'Peso (kg)'), ('altura', 'Altura (cm)'), ('pa_sis', 'PA Sistólica (mmHg)'), ('pa_dia', 'PA Diastólica (mmHg)'), ('fc', 'Frequência Cardíaca (bpm)'), ('temp', 'Temperatura (°C)'), ('glicemia', 'Glicemia (mg/dL)'), ('imc', 'IMC'), ('cintura', 'Circunferência Abdominal (cm)'), ('fcf', 'FCF Fetal (bpm)'), ('au', 'Altura Uterina (cm)'), ('mobilograma', 'Mobilograma (movimentos)')], max_length=20),
        ),
    ]
