# Generated by Django 5.2 on 2026-05-05 17:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_vitalreading_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabMarker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_slug', models.CharField(db_index=True, help_text='ex: "hemograma", "lipidios", "tireoide"', max_length=50)),
                ('category_label', models.CharField(help_text='Display label for the category', max_length=100)),
                ('category_order', models.IntegerField(default=0)),
                ('key', models.CharField(help_text='Stable key per category, ex: "hemoglobina", "ldl", "tsh"', max_length=60)),
                ('label', models.CharField(help_text='Display label', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('value_text', models.CharField(blank=True, help_text='For non-numeric results: "positivo", "↑", "negativo"', max_length=100)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('ref_min', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('ref_max', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('ref_text', models.CharField(blank=True, help_text='For complex refs: "depende fase ciclo", "<190 desejável"', max_length=200)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('alto', 'Alto'), ('baixo', 'Baixo'), ('limite_superior', 'Limite superior'), ('limite_inferior', 'Limite inferior'), ('critico', 'Crítico')], default='normal', max_length=20)),
                ('obs', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(help_text='The collection event this marker belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='api.healthexam')),
                ('profile', models.ForeignKey(help_text='Denormalized for fast queries — must equal exam.profile', on_delete=django.db.models.deletion.CASCADE, related_name='lab_markers', to='api.profile')),
            ],
            options={
                'ordering': ['category_order', 'order', 'key'],
                'indexes': [models.Index(fields=['profile', 'category_slug'], name='api_labmark_profile_080e33_idx'), models.Index(fields=['profile', 'key'], name='api_labmark_profile_b5c9df_idx')],
            },
        ),
    ]
