# Generated by Django 5.2 on 2026-05-29 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_financial_bug_fixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtemplate',
            name='category',
            field=models.ForeignKey(blank=True, help_text='For match_mode=category: the category whose txns auto-fill this item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_templates', to='api.category'),
        ),
        migrations.AddField(
            model_name='recurringtemplate',
            name='expected_floor_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Floor for max_floor_avg expected_source.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='recurringtemplate',
            name='expected_lookback_months',
            field=models.IntegerField(default=3, help_text='Trailing window (closed months) for avg-based expected_source.'),
        ),
        migrations.AddField(
            model_name='recurringtemplate',
            name='expected_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('prev_month', 'Mês anterior'), ('avg_3m', 'Média (N meses)'), ('max_floor_avg', 'Max(piso, média)')], default='manual', help_text='How the monthly expected amount is derived.', max_length=20),
        ),
        migrations.AddField(
            model_name='recurringtemplate',
            name='match_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('category', 'Category')], default='manual', max_length=20),
        ),
    ]
