# Generated by Django 5.2 on 2026-06-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_recurringtemplate_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='pluggy_purchase_date',
            field=models.DateField(blank=True, help_text='Original purchase date of an installment plan (Pluggy creditCardMetadata.purchaseDate); stable anchor for installment de-duplication', null=True),
        ),
    ]
