# Generated by Django 5.2 on 2026-06-18 04:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_add_pluggy_purchase_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentSeriesOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_desc', models.CharField(max_length=255)),
                ('amount_group', models.IntegerField(help_text='round(abs(per-installment amount)) — matches projection dedup')),
                ('total_inst', models.IntegerField(help_text='original N in k/N')),
                ('effective_total', models.IntegerField(help_text='series stops here; projection forecasts no further')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_overrides', to='api.account')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_overrides', to='api.profile')),
            ],
            options={
                'unique_together': {('profile', 'account', 'base_desc', 'amount_group', 'total_inst')},
            },
        ),
    ]
