# Generated by Django 5.2 on 2026-07-15 20:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_installmentseriesoverride'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(choices=[('clinical_report', 'Clinical / pregnancy report'), ('observations', 'Clinical observations'), ('hip_imaging', 'Hip imaging'), ('glucose_log', 'Capillary glucose log'), ('meal_plan', 'Meal plan'), ('shopping_list', 'Shopping list'), ('baby_implications', 'Lab findings -> baby implications')], max_length=50)),
                ('payload', models.JSONField(help_text='Shape is per-slug; consumed by the matching card.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_content', to='api.profile')),
            ],
            options={
                'ordering': ['profile', 'slug'],
                'unique_together': {('profile', 'slug')},
            },
        ),
    ]
