# Generated by Django 5.2 on 2026-08-03 00:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_add_health_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancePipelineRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual'), ('gap_approval', 'Gap approval'), ('maintenance', 'Maintenance window')], db_index=True, default='scheduled', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='The slot this run was meant to fill, so a manual run cannot mask a missed one.', null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('stages', models.JSONField(default=dict, help_text='Per-stage outcome.')),
                ('coverage', models.JSONField(default=dict, help_text='Profiles/accounts/endpoints fully fetched.')),
                ('applied', models.BooleanField(default=False, help_text='False when the mutating stages ran dry.')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['kind', 'finished_at'], name='pipelinerun_kind_fin_idx')],
            },
        ),
        migrations.CreateModel(
            name='BillReconciliationConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_name', models.CharField(help_text='Snapshot, readable after a rename.', max_length=100)),
                ('month_str', models.CharField(db_index=True, max_length=7)),
                ('bill_id', models.CharField(max_length=100)),
                ('stored_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pluggy_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bill_closing_date', models.DateField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('resolution', models.CharField(choices=[('pending', 'Pending'), ('accepted_pluggy', 'Accepted Pluggy total'), ('kept_statement', 'Kept statement total'), ('superseded', 'Superseded by a newer conflict')], db_index=True, default='pending', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_conflicts', to='api.account')),
                ('mapping', models.ForeignKey(blank=True, help_text='Resolution target. Null once the mapping is gone; the snapshot survives.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_conflicts', to='api.recurringmapping')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_conflicts', to='api.profile')),
            ],
            options={
                'ordering': ['-first_seen_at'],
                'indexes': [models.Index(fields=['profile', 'resolution'], name='billconf_prof_res_idx')],
                'constraints': [models.UniqueConstraint(fields=('profile', 'bill_id', 'stored_total', 'pluggy_total'), name='unique_bill_conflict_identity')],
            },
        ),
    ]
