/**
 * Cross-couple medical implications for the baby — synthesized from
 * Palmer's + Rafa's exams that have direct or potential impact on the
 * pregnancy or neonate.
 *
 * Each entry: title, source profile, summary, scenarios (when relevant),
 * concrete actions, drugs/triggers to avoid, priority.
 */

export const BABY_IMPLICATIONS = [
  {
    id: 'g6pd-paterno',
    titulo: 'G6PD — Palmer portador',
    origem: 'Palmer · painel laboratorial 2025-05-28 + genético 2024',
    categoria: 'Genético',
    prioridade: 'alta',
    marker_refs: [
      { profile: 'palmer', category: 'especificos', key: 'g6pd' },
    ],
    resumo: 'Palmer tem deficiência de G6PD confirmada (atividade 2.1 U/gHb · Classe III WHO). Herança ligada ao X recessiva — Palmer é XᵍY. Rafa não testada.',
    cenarios: [
      {
        label: 'Cenário esperado · Rafa XX normal',
        probabilidade: '~95%+ (assumindo sem histórico familiar)',
        filho_homem: '0% afetado',
        filha_mulher: '100% portadora obrigatória (geralmente assintomática)',
      },
      {
        label: 'Cenário pior · Rafa XᵍX portadora',
        probabilidade: 'incomum sem histórico',
        filho_homem: '50% afetado',
        filha_mulher: '50% portadora · 50% homozigota afetada',
      },
    ],
    acoes: [
      'Solicitar genotipagem G6PD da Rafa na 1ª consulta pré-natal (~R$ 200 lab privado)',
      'Avisar pediatra/neonatologista no parto sobre histórico paterno',
      'Confirmar inclusão no teste do pezinho ampliado (SUS desde 2014, cobre G6PD)',
      'Monitorar icterícia neonatal mais de perto — G6PD aumenta risco de hiperbilirrubinemia grave',
      'Se filha portadora: aconselhamento genético quando ela própria for ter filhos',
    ],
    evitar: {
      titulo: 'Fármacos a evitar no RN afetado (e na Rafa se for portadora)',
      itens: [
        'Sulfas — Bactrim, sulfadiazina, sulfasalazina',
        'Nitrofurantoína (comum em ITU — usar amoxicilina/cefalexina)',
        'Dapsona',
        'Primaquina · cloroquina (antimaláricos)',
        'Naftaleno (bolinha de cânfora — guardar roupa)',
        'Anilinas em corantes/tinturas',
        'Fava-bean (favas) — risco se ingerido',
      ],
    },
  },

  {
    id: 'pcr-paterna',
    titulo: 'Investigação inflamatória/EpA Palmer encerrada (mai/2026)',
    origem: 'Palmer · follow-up DASA 2026-04-28 + HLA-B27 liberado 04/05/2026',
    categoria: 'Resolvido',
    prioridade: 'baixa',
    marker_refs: [
      { profile: 'palmer', category: 'inflamatorio', key: 'pcr' },
      { profile: 'palmer', category: 'inflamatorio', key: 'vhs' },
      { profile: 'palmer', category: 'inflamatorio', key: 'hla_b27' },
    ],
    resumo: 'PCR 0.25 mg/dL + VHS 14 mm/h normalizados + HLA-B27 NÃO DETECTADO. Espondiloartropatia (espondilite anquilosante, artrite reativa, psoriásica axial) descartada. Não há doença autoimune sistêmica que possa impactar o neonato. Encaminhamento reumatológico não justificado. Foco 100% em manejo ortopédico (FAI/CAM estrutural) + medicina da dor (genitofemoral).',
    acoes: [
      'Investigação laboratorial inflamatória/genética encerrada',
      'Monitoramento periódico não rotineiro (apenas se sintomas novos)',
      'Foco: manejo ortopédico (fisioterapia, posturologia) + bloqueio diagnóstico genitofemoral',
      'Sem implicações gestacionais — NÃO transmite EpA pra bebê',
    ],
  },

  {
    id: 'idade-materna',
    titulo: 'Idade materna 35 anos',
    origem: 'Rafa · DOB calc 2026-05',
    categoria: 'Risco gestacional',
    prioridade: 'alta',
    resumo: 'Idade materna ≥35 é classificada como gestação tardia. Risco aumentado de cromossomopatias (T21 ~1:350 vs ~1:1100 em 25a), pré-eclâmpsia, diabetes gestacional, baixo peso. Não impede gestação saudável — exige vigilância adicional.',
    acoes: [
      'USG morfológica 1º trimestre (11–13s+6d) com TN, osso nasal, ducto venoso — janela essencial',
      'Considerar NIPT (teste pré-natal não invasivo) ~10s+ — sangue materno, sensibilidade >99% para T21/T18/T13. ~R$ 1.200–2.500 BR, raramente coberto',
      'Rastreio combinado 1º tri (PAPP-A + β-hCG livre) na USG morfológica',
      'TOTG 24–28s essencial (risco DMG aumentado)',
      'Vigilância pressórica reforçada (PA em toda consulta)',
    ],
  },

  {
    id: 'hba1c-historica',
    titulo: 'HbA1c em tendência leve de alta — 5,7→5,1→5,4 (Rafa)',
    origem: 'Rafa · 2024-08-26 (Lapac) · 2025-05-28 (DASA) · 2026-05-06 (DASA painel 1º T)',
    categoria: 'Risco DMG',
    prioridade: 'media',
    marker_refs: [
      { profile: 'rafa', category: 'glicemia', key: 'hba1c' },
      { profile: 'rafa', category: 'glicemia', key: 'glicose' },
    ],
    resumo: 'HbA1c em 2024 estava 5,7% (limite pré-DM), normalizou para 5,1% em 2025, agora 5,4% no painel 1º T (06/05/2026). Ainda dentro do normal (<5,7%) mas em alta sutil. Glicemia jejum 94 (normal), insulina 4,9, HOMA-IR 1,13 — sem resistência. TOTG 24-28s segue essencial.',
    acoes: [
      'TOTG 75g 24–28s — não pular nem postergar (HbA1c 5,4 reforça importância)',
      'Glicemia jejum 1º tri: 94 mg/dL (normal)',
      'HOMA-IR 1,13 (sem resistência insulínica pré-existente)',
      'Se DMG diagnosticada: dieta + monitorização glicêmica domiciliar; insulina se dieta insuficiente',
      'Acompanhamento nutricional preventivo desde o 1º trimestre',
    ],
  },

  {
    id: 'itu-historica',
    titulo: 'Histórico ITU 2024 · urocultura atual negativa ✓',
    origem: 'Rafa · urina I 2024-08-26 · urocultura + urina I 2026-05-06 (DASA)',
    categoria: 'Risco infeccioso',
    prioridade: 'baixa',
    resumo: 'Urina I de 2024 sugestiva de ITU/contaminação. No painel 1º T (06/05/2026): urocultura NEGATIVA, urina I sem proteína/glicose/nitrito/Hb, leucócitos 7.400/mL e hemácias 7.800/mL (ambos normais). Sem bacteriúria assintomática atual. Manter vigilância pela história prévia.',
    acoes: [
      'Urocultura 06/05/2026: negativa · urina I normal',
      'Urocultura em TODA consulta pré-natal (não apenas urina I) — história 2024 mantém vigilância',
      'Tratar bacteriúria assintomática (>100k UFC) mesmo sem sintomas, se aparecer',
      'Antibiótico de escolha: cefalexina ou amoxicilina (G6PD-safe se filha portadora)',
      'EVITAR nitrofurantoína no 3º trimestre (risco hemólise neonatal) e em qualquer fase se filha for portadora G6PD',
    ],
  },

  {
    id: 'trombocitose-leve',
    titulo: 'Plaquetas normalizaram (464k → 396k) ✓',
    origem: 'Rafa · hemograma 2025-05-28 · hemograma 1º T 2026-05-06 (DASA)',
    categoria: 'Resolvido',
    prioridade: 'baixa',
    marker_refs: [
      { profile: 'rafa', category: 'hemograma', key: 'plaquetas' },
    ],
    resumo: 'Trombocitose leve de maio/2025 (464k) era reativa — no painel 1º T (06/05/2026) plaquetas em 396k, dentro da referência. Sem indicação para monitoramento adicional além da rotina hematológica trimestral.',
    acoes: [
      'Plaquetas 1º T: 396.000/µL (dentro do normal)',
      'Manter hemograma trimestral como rotina pré-natal',
      'Vigilância para sinais de HELLP no 3º tri (cefaleia, dor epigástrica, edema súbito) — independente desta normalização',
    ],
  },

  {
    id: 'reservas-nutricionais',
    titulo: 'Reservas nutricionais Rafa — adequadas e em alta ✓',
    origem: 'Rafa · 2025-05-28 (DASA) · painel 1º T 2026-05-06 (DASA)',
    categoria: 'Proteção',
    prioridade: 'baixa',
    marker_refs: [
      { profile: 'rafa', category: 'micronutrientes', key: 'ferro' },
      { profile: 'rafa', category: 'micronutrientes', key: 'ferritina' },
      { profile: 'rafa', category: 'micronutrientes', key: 'b12' },
      { profile: 'rafa', category: 'micronutrientes', key: 'vit_d' },
    ],
    resumo: 'Reservas em trajetória positiva: ferro 110→143 µg/dL ↑, ferritina 33,8→58,4 ng/mL ↑, B12 atual 453 pg/mL. Hemoglobina 13,0 g/dL (sem anemia). Folato 23,6 ng/mL e vit D 40,8 em 2025 (ambos ótimos). Vit D atual aguardando coleta avulsa (autorização Amil pendente).',
    acoes: [
      'Ferro 143 · Ferritina 58,4 · B12 453 (todos normais, trajetória de alta)',
      'Hb 13,0 — sem anemia. Reservas suficientes para expansão de volume 2º/3º T',
      'Coletar 25-OH Vitamina D — não veio no painel 1º T, autorização Amil pendente',
      'Ogestan-Pré em uso desde 05/05/2026 (cobre fólico + iodo + micronutrientes)',
      'Repetir ferritina + B12 + Hb no 3º tri (rastreio anemia gestacional)',
      'Vitamina D suplementar 1000–2000 UI/dia mantém faixa ótima (>30 ng/mL)',
    ],
  },

  {
    id: 'tireoide-rafa',
    titulo: 'TSH 0,56 — dentro da faixa gestacional 1º T ✓',
    origem: 'Rafa · 2025-05-28 (DASA) · painel 1º T 2026-05-06 (DASA)',
    categoria: 'Endócrino',
    prioridade: 'baixa',
    marker_refs: [
      { profile: 'rafa', category: 'tireoide', key: 'tsh' },
      { profile: 'rafa', category: 'tireoide', key: 't4_livre' },
    ],
    resumo: 'TSH atual 0,56 µUI/mL (referência gestacional 1º T: 0,10–3,60), caiu de 0,96 em 2025 — esperado pela supressão pelo hCG. T4 livre 1,37 ng/dL (ref 0,70–1,90). Anti-TPO e anti-Tg negativos em 2025 (sem autoimunidade). Sem hipotireoidismo gestacional.',
    acoes: [
      'TSH 0,56 · T4L 1,37 — dentro da faixa 1º T com folga',
      'Repetir TSH + T4 livre ~12 sem (~junho/2026) para confirmar estabilização pós-pico hCG',
      'Meta gestacional: 1º T 0,10–3,60 · 2º T 0,40–4,30 · 3º T 0,40–4,30 (Dasa) · ATA: <2,5 no 1º T',
      'Se subir acima da meta: levotiroxina precoce (tireoide tem demanda 30–50% maior na gestação)',
    ],
  },

  {
    id: 'cobertura-amil',
    titulo: 'Carência obstétrica Amil 300d — RESOLVIDO via Proasa Rafa paralelo',
    origem: 'Áudio corretor Luiz Carvalho 04/05/2026 + Proasa adesão 06/05/2026',
    categoria: 'Cobertura assistencial',
    prioridade: 'media',
    resumo: 'Carência Amil 300d obstétrica permanece intransponível (DPP cai ~50d antes do fim). MAS Rafa reativada na Proasa ADV 300 DF em 06/05/2026 com TODAS as carências aproveitadas → cobertura obstétrica disponível imediatamente via plano paralelo. Risco mitigado. Amil mantém-se como cobertura ambulatorial principal de ambos.',
    acoes: [
      'Honorários Dra. Nahara (parto): R$ 10.000 informado pela médica',
      'Hospital mid-high Brasília (Maternidade Brasília, Anchieta, Santa Luzia): ~R$ 15-22k pacote',
      'Hospital top (DF Star / São Luiz Star): ~R$ 19-25k pacote (ref R$ 19.800 mar/2025)',
      'Reserva mínima recomendada: R$ 35-40k (cenário esperado sem UTI)',
      'Reserva ideal: R$ 50-70k (margem UTI neonatal 3-5 dias × R$ 5-10k/dia)',
      'Alternativa: manter Nova Saúde paralelo ~R$ 2-3k/mês × 8 meses = R$ 16-24k → equivale a cobertura particular E remove risco UTI (R$ 50-100k mitigado)',
      'Pré-cadastro HMIB (Hospital Materno Infantil Brasília) como rede SUS de referência (backup)',
      'Lei 9656/98 cobre apenas emergência obstétrica 24h pós-vigência (intercorrências graves, não parto eletivo)',
      'Detalhes em family/finance/projecao_parto.md',
    ],
  },
  {
    id: 'proasa-rafa-ativo',
    titulo: 'Rafa reativada Proasa ADV 300 DF — carências aproveitadas ✓',
    origem: 'Adesão confirmada 06/05/2026 via Easyplan · family/finance/proposta_proasa_easyplan.md',
    categoria: 'Cobertura assistencial',
    prioridade: 'alta',
    resumo: 'Rafa adesão confirmada Proasa ADV 300 DF (enfermaria, R$ 503,67/mês) com TODAS as carências cumpridas aproveitadas — incluindo internação obstétrica. Upgrade pra ADV 400 DF (apartamento) só viável a partir de outubro/2026. Maternidades particulares Brasília só têm apartamento pra parto, então: (a) sobe pra ADV 400 em outubro (se sem nova carência) → parto em apto coberto, OU (b) fica no ADV 300 e paga upgrade direto ao hospital ~R$ 1.500-4.500.',
    acoes: [
      'IMEDIATO: Salvar em PDF a carta de aproveitamento de carências + contrato/condições gerais ADV 300 DF',
      'Setembro/2026: Pedir Easyplan POR ESCRITO se upgrade ADV 300 → ADV 400 gera nova carência (pela RN 438/2018 não pode, mas confirmar)',
      'Outubro/2026: Efetuar upgrade pra ADV 400 DF se confirmado sem carência adicional',
      'Pré-parto: Confirmar com Maternidade Brasília se aceita ADV 400 e custo exato do upgrade enfermaria→apto (caso fique no 300)',
      'Custo total estimado: R$ 5-6k (cenário ótimo ADV 300→400) ou R$ 6-9k (ficar ADV 300 + upgrade hospital)',
      'Mensalidade conjunta agora: R$ 900 Amil + R$ 503 Proasa Rafa = R$ 1.403/mês (R$ 597 abaixo do que pagavam Nova Saúde anterior R$ 2.000)',
      'Atualizar Pregnancy.notes no Vault com plano paralelo (Amil principal + Proasa ADV 300 Rafa)',
    ],
  },
  {
    id: 'orcamento-parto',
    titulo: 'Orçamento total real — R$ 17,8-21,8k (com Proasa) vs R$ 31-38k (só Amil)',
    origem: 'NFS-e 10500 (consulta R$450 confirmado) + Proasa adesão 06/05',
    categoria: 'Financeiro',
    prioridade: 'alta',
    resumo: 'Dra. Nahara fora da rede Proasa — honorários (R$ 5,85k consultas R$450/cada × 13 + R$ 10k parto = R$ 15,85k) são out-of-pocket sempre. Proasa cobre HOSPITAL: internação, sala de parto, equipe plantonista, UTI neonatal eventual. Total realista com Proasa: R$ 17,8-21,8k esperado (vs R$ 31-38k só Amil). Economia real R$ 13-16k esperado, R$ 50-65k se UTI necessária.',
    acoes: [
      'Out-of-pocket Dra. Nahara: 13 consultas × R$450 = R$5,85k + R$10k parto = R$15,85k total (fora rede Proasa)',
      'Plano Proasa cobre: hospital + internação + equipe plantão + UTI neonatal eventual',
      'Mensalidade Proasa Rafa: R$503/mês × 8 meses = R$4k (+ copay R$500-1500)',
      'Upgrade enfermaria→apto no parto (ADV 300): R$1.5-4.5k direto ao hospital — OU subir pra ADV 400 em outubro',
      'Pedir Easyplan/Proasa TABELA DE REEMBOLSO para profissionais fora da rede — pode recuperar R$2-5k dos R$16.5k Dra. Nahara',
      'Reserva alvo: R$25-30k em conta de liquidez (cobre gap esperado + margem)',
      'UTI neonatal coberta integralmente pela Proasa — R$50-100k de risco mitigado',
      'Detalhes em family/finance/projecao_parto.md + proposta_proasa_easyplan.md',
    ],
  },
  {
    id: 'pedidos-1tri-2026-05-05',
    titulo: '1ª consulta + painel 1º T concluídos ✓ · USG 18/05 · Vit D pendente',
    origem: 'Dra. Nahara A. G. Torres (CRM-DF 18529, Grupo Elas) · consulta 05/05/2026 · labs 06/05/2026 · laudo 10/05/2026',
    categoria: 'Pré-natal · 1º trimestre',
    prioridade: 'alta',
    resumo: 'Painel 1º T concluído com 21/22 exames coletados (Vit D pendente por autorização Amil). Resultados: 12/13 categorias dentro da referência. 3 ações decorrentes: vacinar Hep B (Anti-HBs <2), reforçar prevenção toxoplasmose (suscetível, IgG negativa), coletar Vit D. USG transvaginal datação agendada 18/05/2026 (~IG 7+4).',
    acoes: [
      'Painel 1º T coletado 06/05/2026, laudo entregue 10/05/2026',
      'Verde no atacado: HIV/HBV/HCV/HTLV/sífilis não reagentes; rubéola e CMV imunes; tipagem O Rh+; sem ITU; tireoide e metabolismo normais',
      'Discutir vacina hep B na 2ª consulta (Anti-HBs <2,0 mUI/mL)',
      'Repetir sorologia toxoplasmose a cada trimestre (~ago/2026 e ~nov/2026) — Rafa suscetível',
      'Vitamina D (25-OH) aguardando autorização Amil — coletar avulsa',
      'USG transvaginal datação: 18/05/2026 (~IG 7+4) — coberta pela Proasa desde adesão 06/05; Amil libera só em 28/05',
      'Próxima consulta Dra. Nahara: ~05/06/2026 (1 mês após 1ª)',
      'Ogestan-Pré em uso desde 05/05',
      'Análise detalhada: health/family/pregnancy/exames/2026-05-06_painel_1tri/analise.md',
    ],
  },

  {
    id: 'hepatite-b-vacinar',
    titulo: 'Hepatite B — Rafa sem proteção vacinal (Anti-HBs <2,0)',
    origem: 'Rafa · painel 1º T 2026-05-06 (DASA, Dra. Nahara)',
    categoria: 'Imunização',
    prioridade: 'alta',
    marker_refs: [
      { profile: 'rafa', category: 'sorologias', key: 'hbsag' },
      { profile: 'rafa', category: 'sorologias', key: 'anti_hbs' },
    ],
    resumo: 'Anti-HBs <2,0 mUI/mL — sem proteção contra hepatite B (precisa ≥10 para imunidade). HBsAg negativo confirma ausência de infecção, abrindo janela segura para vacinação durante a gestação. Hep B materna crônica pode transmitir verticalmente no parto — proteção prévia da mãe protege também o neonato.',
    acoes: [
      'Discutir na 2ª consulta Dra. Nahara (~05/06/2026) esquema de vacinação Engerix-B',
      'Esquema acelerado: 0/1/2 meses (3 doses em 60 dias) — recomendado se janela curta',
      'Esquema padrão: 0/1/6 meses — completa após parto se necessário',
      'Vacina hep B considerada segura em qualquer trimestre (SBIM, CDC, MS)',
      'Hep B materna na gestação não-vacinada: vacinação + imunoglobulina anti-HBs no RN nas primeiras 12h se mãe HBsAg+ (aqui não aplica — HBsAg negativo)',
      'Repetir Anti-HBs ~2 meses após última dose para confirmar resposta',
    ],
  },

  {
    id: 'toxoplasmose-suscetivel',
    titulo: 'Toxoplasmose — Rafa suscetível (IgG negativa)',
    origem: 'Rafa · painel 1º T 2026-05-06 (DASA, Dra. Nahara)',
    categoria: 'Risco infeccioso',
    prioridade: 'alta',
    marker_refs: [
      { profile: 'rafa', category: 'sorologias', key: 'toxo_igg' },
      { profile: 'rafa', category: 'sorologias', key: 'toxo_igm' },
    ],
    resumo: 'Toxoplasmose IgG <0,2 UI/mL (não reagente) + IgM 0,06 (não reagente). Sem imunidade prévia → Rafa suscetível durante toda a gestação. Soroconversão pode causar toxoplasmose congênita (calcificações cerebrais, coriorretinite, hidrocefalia). Prevenção alimentar/ambiental + repetição trimestral da sorologia.',
    acoes: [
      'Repetir IgG/IgM toxoplasmose em ~agosto/2026 (2º T) e ~novembro/2026 (3º T)',
      'Se IgM positivar em qualquer momento: PCR no líquido amniótico + tratamento (espiramicina/pirimetamina-sulfa conforme IG) — manejo Dra. Nahara',
      'Carne MUITO bem passada (sem rosado central). Sushi só com procedência ultra-segura ou evitar',
      'Lavar verduras e frutas com hipoclorito (1 colher de sopa / litro de água por 15 min)',
      'Congelar carnes >24h a −12°C antes de cozinhar (mata cistos)',
      'Luvas para jardinagem e manuseio de terra',
      'Palmer assume caixa de areia do gato (ou Rafa com luvas + lavagem das mãos)',
      'Evitar contato direto com fezes de gato e areia de gatos errantes',
    ],
  },

  {
    id: 'imunidades-confirmadas',
    titulo: 'Imunidades confirmadas: rubéola + CMV ✓',
    origem: 'Rafa · painel 1º T 2026-05-06 (DASA, Dra. Nahara)',
    categoria: 'Proteção',
    prioridade: 'baixa',
    marker_refs: [
      { profile: 'rafa', category: 'sorologias', key: 'rubeola_igg' },
      { profile: 'rafa', category: 'sorologias', key: 'cmv_igg' },
    ],
    resumo: 'Rubéola IgG 90,5 UI/mL (imune) + IgM negativo. CMV IgG 147 UA/mL (infecção passada) + IgM negativo. Ambos com imunidade estabelecida — risco de transmissão vertical reduzido drasticamente. Sífilis, HIV, HCV, HTLV, HBsAg: todos não reagentes.',
    acoes: [
      'Rubéola: imune (sem necessidade de tríplice viral pós-parto)',
      'CMV: infecção passada, IgG positivo + alta avidez presumida — risco vertical baixíssimo',
      'HIV, sífilis, HCV, HTLV, HBsAg: todos não reagentes',
      'Repetir sorologias críticas no 3º trimestre conforme protocolo MS (HIV, sífilis, HBsAg)',
    ],
  },

  {
    id: 'nfe-reembolso-cpf',
    titulo: 'NFs no CPF do Palmer · pode dificultar reembolso Proasa Rafa',
    origem: 'NFS-e 10500 (1ª consulta 05/05/2026) · family/pregnancy/notas_fiscais.md',
    categoria: 'Operacional',
    prioridade: 'alta',
    resumo: '1ª NF emitida no CPF do Palmer (titular financeiro) com paciente Rafa. Operadoras geralmente exigem NF no nome do beneficiário do plano. Como Proasa é plano da Rafa, pode complicar reembolso ~R$ 3-5k estimado das consultas + parto.',
    acoes: [
      'Confirmar com Easyplan/Proasa: NF deve estar no CPF do beneficiário (Rafa) ou aceita CPF do tomador?',
      'Se exigir Rafa: pedir reemissão da NFS-e 10500 no CPF da Rafa (040.378.591-06)',
      'Para próximas ~12 consultas: pedir NF já no CPF da Rafa desde o início',
      'Para o parto: idem — emissão direto no CPF da Rafa',
      'Pedir Easyplan tabela de reembolso vigente ADV 300 DF (consultas + parto)',
      'Reembolso estimado: R$ 3-5k dos R$ 15.850 out-of-pocket (~20-30%)',
    ],
  },
  {
    id: 'orientacoes-dra-nahara-1tri',
    titulo: 'Orientações Dra. Nahara — 1º trimestre (alimentação, atividade, cosméticos)',
    origem: '6 docs entregues 1ª consulta · family/pregnancy/orientacoes_dra_nahara.md',
    categoria: 'Orientação clínica',
    prioridade: 'media',
    resumo: 'Material entregue pela Dra. Nahara cobre frequência das consultas (mensal até 32-34s, quinzenal 34-37s, semanal 37+), alterações fisiológicas 1º tri, guia alimentar (recomendados/proibidos), chás permitidos/proibidos, atividade física (150min/sem moderado), maquiagem/cosméticos.',
    acoes: [
      'Frequência consultas Dra. Nahara: mensal até 32-34s, quinzenal 34-37s, semanal 37s-parto = ~13 consultas × R$450 = R$ 5.850 (NFS-e 10500 confirmou valor)',
      'Janelas: mensal→quinzenal ~13/11/2026, quinzenal→semanal ~10/12/2026',
      'Alimentos a EVITAR: carnes cruas/malpassadas, peixes alto mercúrio (tubarão/peixe-espada), queijos não pasteurizados, ovos crus, embutidos, álcool. Cafeína máx 200mg/dia.',
      'Chás PROIBIDOS: canela, boldo, carqueja, hibisco, sene, losna, confrei, chá verde/preto/mate. Permitidos: camomila, erva-doce, capim-limão, gengibre (1g/dia), hortelã.',
      'Atividade física: 150min/sem moderado (caminhada, natação, hidroginástica, yoga leve, Kegel diário). Evitar contato, queda, mergulho.',
      'Cosméticos a EVITAR: retinoides, hidroquinona, formaldeído, ftalatos, parabenos, amônia, alisamento com formol, óleos essenciais agressivos. Botox/peeling profundo/laser proibidos.',
      'Filtro solar: usar APENAS filtros físicos/minerais (óxido de zinco, dióxido de titânio) — evitar oxibenzona.',
      'Sintomas 1º tri esperados melhoram entre 12-14 sem, alívio significativo até 20 sem',
      'Detalhes completos em family/pregnancy/orientacoes_dra_nahara.md',
    ],
  },
  {
    id: 'amil-coberturas-imediatas',
    titulo: 'Cobertura Amil já disponível para pré-natal',
    origem: 'Tabela ANS PRC 609 + áudio corretor 04/05/2026',
    categoria: 'Cobertura assistencial',
    prioridade: 'baixa',
    resumo: 'Apesar do parto não estar coberto, todo o pré-natal está. PRC 609 reduz quase tudo. Para Bronze DF: copay isento em consultas, exames, internação não-obstétrica. Terapias (fisio/fono/nutri/psico/TO) com 40% até R$60/sessão.',
    acoes: [
      'Consultas pré-natal: carência 1 dia · cobertas desde 29/04/2026',
      'Exames laboratoriais básicos: carência 1 dia · cobertos desde 29/04/2026',
      'USG (datação, morfológica, obstétrica): carência 30 dias · libera 28/05/2026',
      'TC/RM/cardio: carência 30 dias · libera 28/05/2026',
      'Internação clínica não-obstétrica: carência 60 dias · libera 27/06/2026',
      'Cirurgia day-hospital não-obstétrica: carência 60 dias · libera 27/06/2026',
      'Hemoterapia: carência 90 dias · libera 27/07/2026',
      'Psicoterapia + Nutrição (suporte gestacional/pós-parto): carência 180 dias · libera 25/10/2026',
      '(Datas exatas estão computadas em PregnancySerializer.carencias e renderizadas no widget de conflitos.)',
    ],
  },

  {
    id: 'tipagem-sanguinea',
    titulo: 'Tipagem Rafa O Rh Positivo + Coombs negativo — sem risco DHRN ✓',
    origem: 'Rafa · painel 1º T 2026-05-06 (DASA, Dra. Nahara)',
    categoria: 'Resolvido',
    prioridade: 'baixa',
    marker_refs: [
      { profile: 'rafa', category: 'tipagem', key: 'grupo_abo' },
      { profile: 'rafa', category: 'tipagem', key: 'fator_rh' },
      { profile: 'rafa', category: 'tipagem', key: 'coombs_indireto' },
    ],
    resumo: 'Rafa tipou O Rh Positivo com Coombs indireto negativo. Como Rh+, não desenvolve anticorpos anti-D — risco de doença hemolítica perinatal (DHRN) nulo independentemente do tipo do Palmer. Sem necessidade de imunoglobulina anti-D na 28ª semana nem pós-parto.',
    acoes: [
      'Tipagem Rafa confirmada O Rh Positivo · Coombs indireto negativo',
      'Imunoglobulina anti-D NÃO indicada (28ª sem ou pós-parto)',
      'Coombs indireto repetir 28s como rotina pré-natal padrão (independente)',
      'Tipagem Palmer permanece não documentada — irrelevante para risco DHRN, mas útil registrar em algum hemograma futuro',
    ],
  },

  {
    id: 'vacinacao-mae',
    titulo: 'Vacinação materna — proteção neonatal indireta',
    origem: 'Calendário MS gestante',
    categoria: 'Imunização',
    prioridade: 'alta',
    resumo: 'Vacinas maternas durante gestação criam imunidade passiva no neonato (anticorpos via placenta) — proteção crítica nos primeiros meses antes do bebê iniciar próprio calendário vacinal.',
    acoes: [
      'dTpa (coqueluche) — 27–36s · idealmente 28s · cada gestação · CRÍTICA para proteção neonatal contra coqueluche',
      'Influenza — qualquer trimestre durante campanha (abril–maio BR)',
      'COVID-19 — conforme calendário vigente, segura em qualquer trimestre',
      'Hepatite B — 3 doses se não vacinada previamente, qualquer trimestre',
      'EVITAR: tríplice viral (SCR), varicela, febre amarela durante gestação (vivas atenuadas)',
    ],
  },

  {
    id: 'exposicoes-ambientais',
    titulo: 'Exposições ambientais a evitar',
    origem: 'Diretrizes ACOG + MS',
    categoria: 'Prevenção',
    prioridade: 'media',
    resumo: 'Itens domésticos comuns que devem ser evitados ou minimizados durante a gestação.',
    acoes: [
      'Naftaleno (bolinha de cânfora) — proibido por causa do G6PD paterno + risco fetal genérico. Substituir por alternativas naturais (cravo, lavanda)',
      'Tintura de cabelo — evitar 1º tri; após 2º tri preferir vegetal sem amônia',
      'Carne crua/mal passada + leite não pasteurizado — risco toxoplasmose/listeria',
      'Gato sem vermifugação atualizada — limpar caixa de areia com luvas (toxoplasma)',
      'Álcool — abstinência total recomendada',
      'Cafeína — limitar a 200mg/dia (~1 espresso ou 2 cafés filtrados)',
      'Atum/peixe-espada e peixes grandes — limitar (mercúrio); priorizar salmão, sardinha',
    ],
  },
]

export const PRIORIDADE_LABEL = {
  alta: 'alta prioridade',
  media: 'média prioridade',
  baixa: 'baixa prioridade',
}
