# -*- coding: utf-8 -*-
"""Mapa rótulo → chave de ícone. Regras por palavra-chave, na ordem:
a primeira que casar vence, então o mais específico vem antes."""

RULES = [
    # roupa
    ('saída de maternidade', 'saida'),
    # variantes de body são peças diferentes — cada uma com seu desenho
    ('body manga longa', 'body-ml'),
    ('body regata', 'body-regata'),
    ('body manga curta', 'body-mc'),
    ('body', 'body-mc'),
    ('pagão', 'pagao'),
    ('macacão manga longa', 'macacao'),
    ('macaquinho', 'macaquinho'),
    ('macacão', 'macacao'),
    ('mijão', 'mijao'),
    ('shorts', 'shorts'),
    ('casaquinho', 'casaquinho'),
    ('meias', 'meias'),
    ('chapéu', 'chapeu'),
    ('touca', 'touca'),
    ('babador', 'babador'),
    ('fralda de pano', 'pano'),
    ('pano de boca', 'pano'),
    ('manta média', 'manta-media'),
    ('manta', 'manta-leve'),
    ('saco de dormir', 'saco-dormir'),
    ('cueiro', 'cueiro'),
    ('vestidinho', 'vestido'),
    ('lavar tudo', 'lavar'),
    ('trocas de roupa', 'roupa-dobrada'),
    ('roupa confortável', 'roupa-dobrada'),
    # quarto
    ('berço', 'berco'),
    ('colchão firme', 'colchao'),
    ('protetor de colchão', 'protetor-colchao'),
    ('lençol', 'lencol'),
    ('cômoda', 'comoda'),
    ('poltrona', 'poltrona'),
    ('babá eletrônica', 'baba-eletronica'),
    ('luz noturna', 'luz-noturna'),
    ('cortina', 'cortina'),
    ('umidificador', 'umidificador'),
    # banho
    ('banheira', 'banheira'),
    ('toalha', 'toalha'),
    ('sabonete', 'sabonete'),
    ('calcinha', 'calcinha'),
    ('algodão', 'algodao'),
    ('gaze', 'gaze'),
    ('pente', 'pente'),
    ('tesourinha', 'tesourinha'),
    ('termômetro de banho', 'termometro-banho'),
    ('termômetro digital', 'termometro'),
    # fraldas
    ('fralda descartável rn', 'fralda'),
    ('fraldas rn', 'fralda'),
    ('fralda descartável p', 'fralda-pacote'),
    ('fraldas tamanho', 'fralda-pacote'),
    ('bolsa de passeio', 'bolsa'),
    ('trocador', 'trocador'),
    ('pomada', 'pomada'),
    ('lenços umedecidos', 'lencos'),
    ('lixeira', 'lixeira'),
    # farmácia
    ('soro fisiológico', 'soro'),
    ('aspirador nasal', 'aspirador'),
    ('álcool 70', 'alcool'),
    ('antitérmico', 'receita'),
    ('lista de contatos', 'contatos'),
    # amamentação
    ('sutiã', 'sutia'),
    ('absorvente de seio', 'absorvente-seio'),
    ('absorventes de seio', 'absorvente-seio'),
    ('absorvente pós-parto', 'absorvente-pos'),
    ('lanolina', 'lanolina'),
    ('almofada de amamentação', 'almofada'),
    ('consultora', 'apoio'),
    ('potes ou sacos', 'potes-leite'),
    # passeio
    ('bebê conforto', 'bebe-conforto'),
    ('carrinho', 'carrinho'),
    ('sling', 'sling'),
    ('sombrinha', 'sombrinha'),
    # documentos / mala
    ('rg e cpf', 'documento'),
    ('carteirinha', 'carteirinha'),
    ('caderneta', 'caderneta'),
    ('plano de parto', 'plano-parto'),
    ('comprovante', 'comprovante'),
    ('camisola', 'camisola'),
    ('robe', 'robe'),
    ('nécessaire', 'necessaire'),
    ('chinelo', 'robe'),
    ('carregador', 'carregador'),
    ('lanches', 'lanche'),
    # chá de bebê
    ('vale-presente', 'vale'),
    ('cotização', 'presente'),
    ('produtos de banho', 'sabonete'),
]

FALLBACK = 'check'


def icon_for(label):
    low = label.lower()
    for needle, key in RULES:
        if needle in low:
            return key
    return FALLBACK


# descrição do que desenhar, para a encomenda das ilustrações
SPEC = {
    'body': 'baby bodysuit / onesie, short sleeves, snap crotch',
    'macacao': 'baby footed sleepsuit, long sleeves with feet',
    'macaquinho': 'baby romper, short sleeves and short legs',
    'mijao': 'baby pants with soft waistband',
    'shorts': 'baby shorts',
    'casaquinho': 'small knitted cardigan with two buttons',
    'meias': 'pair of small baby socks',
    'chapeu': 'sun hat with wide brim',
    'touca': 'baby beanie hat',
    'babador': 'baby bib with neck fastening',
    'pano': 'folded muslin cloth square',
    'manta': 'folded soft blanket with a wavy edge',
    'saco-dormir': 'baby sleeping bag / sleep sack, sleeveless',
    'cueiro': 'swaddle wrap cloth, loosely folded',
    'vestido': 'tiny baby dress on a hanger',
    'saida': 'special going-home outfit with a little bow',
    'lavar': 'washing machine with a porthole door',
    'roupa-dobrada': 'neat stack of three folded clothes',
    'berco': 'wooden crib with vertical bars',
    'colchao': 'mattress seen from the side, firm and thick',
    'protetor-colchao': 'fitted mattress protector sheet with elastic corners',
    'lencol': 'folded bed sheet with rounded corner',
    'comoda': 'chest of drawers with a changing top',
    'poltrona': 'comfortable armchair, side view',
    'baba-eletronica': 'baby monitor device with antenna and small screen',
    'luz-noturna': 'small night lamp with soft glow lines',
    'cortina': 'window with a blackout curtain drawn to one side',
    'umidificador': 'humidifier with steam curls rising',
    'banheira': 'baby bathtub with a stand',
    'toalha': 'hooded baby towel',
    'sabonete': 'pump bottle of liquid soap',
    'algodao': 'cotton balls, a small pile of three',
    'gaze': 'gauze pad square with woven texture',
    'pente': 'baby hairbrush with soft bristles',
    'tesourinha': 'round-tip baby scissors',
    'termometro-banho': 'bath thermometer floating, duck-shaped or round dial',
    'termometro': 'digital thermometer stick with display',
    'fralda': 'disposable diaper, closed, seen from front',
    'trocador': 'changing mat, padded with raised sides',
    'pomada': 'squeeze tube of ointment with cap',
    'lencos': 'pack of wet wipes with one wipe pulled out',
    'lixeira': 'small bin with a lid and pedal',
    'soro': 'saline ampoule / small dropper vial',
    'aspirador': 'nasal aspirator bulb with a soft tip',
    'alcool': 'spray bottle of alcohol with trigger',
    'receita': 'prescription paper with a cross mark and pen line',
    'contatos': 'telephone handset with a small note card',
    'sutia': 'nursing bra with clip detail',
    'absorvente-seio': 'round breast pad disc, two overlapping',
    'absorvente-pos': 'sanitary pad, elongated with wings',
    'lanolina': 'small tube of lanolin cream',
    'almofada': 'crescent-shaped nursing pillow',
    'apoio': 'two hands cradling a heart',
    'potes-leite': 'milk storage bottle with measurement lines and lid',
    'bebe-conforto': 'infant car seat with carry handle',
    'carrinho': 'baby stroller / pram, side view',
    'sling': 'baby wrap sling, fabric loop over shoulder',
    'bolsa': 'diaper bag with front pocket and strap',
    'sombrinha': 'parasol / small umbrella open',
    'documento': 'identity card with a small photo square',
    'carteirinha': 'insurance card with a cross symbol',
    'caderneta': 'small notebook with a heart on the cover',
    'plano-parto': 'sheet of paper with lines and a pen',
    'calcinha': 'high-waist cotton underwear',
    'camisola': 'nightgown with front opening',
    'robe': 'bathrobe with a belt tied',
    'necessaire': 'toiletry pouch with zipper',
    'carregador': 'power bank with a charging cable',
    'lanche': 'water bottle beside a snack bar',
    'vale': 'gift card with a small ribbon',
    'presente': 'wrapped gift box with a bow',
    'check': 'simple rounded checkmark inside a circle',
}
